### ISSUE TITLE
[Staking App] Current Epoch distribution shows for disabled dials

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#207] opened 2022-09-08 07:14 UTC
**Describe the bug**
The dials page shows distribution for current and past epoch for disabled dials.

**To Reproduce**
1. Go to https://staking.mstable.app/#/dials
2. See top box

**Expected behavior**
Dials that are disabled should not receive MTA, there is no distribution. So for the past and the current epoch it should show the correct distribution and amount

**Screenshots**
![Screen Shot 2022-09-08 at 14 13 31](https://user-images.githubusercontent.com/69167058/189058588-0fdbdbab-83bc-4386-be98-109e33c99e96.png)

**Comment by toniocodo** [comment] 2022-10-13 10:38
Duplicate of #217

**Closed by toniocodo** 2022-10-13 10:38 UTC
Labels: bug, ui, p3-comp, frontend
